-- Bookrary Manga Dataset Seeds (100 Titles)
-- Location: Database/seeds/mangaSeed.sql

INSERT INTO manga (mangaId, title, author, coverImage, bannerImage, synopsis, totalVolumes, status, category, genres, likeAmount, dislikeAmount, favoriteAmount, rating) VALUES
(1, 'JUJUTSU KAISEN', 'Gege Akutami', '/img/jujustu kaisen.jpg', 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=1200&auto=format&fit=crop&q=80', 'Jujutsu Kaisen follows Yuji Itadori, a high school student who joins a secret organization of Jujutsu Sorcerers to eliminate a powerful Curse named Ryomen Sukuna after consuming a cursed finger.', 30, 'Completed', 'Top Favorite', '["Shonen","Action","Supernatural","Dark Fantasy"]', 14200, 320, 9800, 4.80),
(2, 'ATTACK ON TITAN', 'Hajime Isayama', '/img/attack on titan poster.jpg', 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=1200&auto=format&fit=crop&q=80', 'After his hometown is destroyed and his mother is killed, young Eren Jaeger vows to cleanse the earth of the giant humanoid Titans that have brought humanity to the brink of extinction.', 34, 'Completed', 'Top Favorite', '["Action","Dark Fantasy","Supernatural","Seinen"]', 25400, 410, 18500, 4.90),
(3, 'SOLO LEVELING', 'Chugong', '/img/Poster Solo Leveling.jpg', 'https://images.unsplash.com/photo-1563089145-599997674d42?w=1200&auto=format&fit=crop&q=80', 'In a world where hunters must battle deadly monsters to protect humanity, Sung Jinwoo, the weakest hunter of all, gains a mysterious system allowing him to level up without limits.', 14, 'Completed', 'Top Favorite', '["Action","Fantasy","Supernatural"]', 19800, 290, 15400, 4.90),
(4, 'ONE PIECE', 'Eiichiro Oda', '/img/download (1).jpg', 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1200&auto=format&fit=crop&q=80', 'Monkey D. Luffy sets off on an epic maritime journey with his Straw Hat Pirates to find the legendary treasure known as One Piece and become King of the Pirates.', 108, 'Ongoing', 'Top Favorite', '["Shonen","Action","Adventure","Comedy","Fantasy"]', 42000, 600, 31000, 4.95),
(5, 'DEMON SLAYER', 'Koyoharu Gotouge', '/img/_Demon Slayer_.jpg', 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=1200&auto=format&fit=crop&q=80', 'Tanjiro Kamado sets out to become a demon slayer after his family is slaughtered and his younger sister Nezuko is turned into a demon.', 23, 'Completed', 'Top Favorite', '["Shonen","Action","Supernatural","Historical"]', 22100, 380, 16700, 4.85),
(6, 'DANDADAN', 'Yukinobu Tatsu', '/img/dandadan.jpg', 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=1200&auto=format&fit=crop&q=80', 'Momo Ayase, who believes in ghosts, and Ken Takakura, who believes in aliens, clash over their supernatural beliefs until bizarre events prove both are terrifyingly real.', 20, 'Ongoing', 'Trending', '["Action","Comedy","Supernatural","Sci-Fi","Romance"]', 11200, 190, 8400, 4.80),
(7, 'THE APOTHECARY DIARIES', 'Natsu Hyuuga', '/img/kusuriya no hitorigoto official art.jpg', 'https://images.unsplash.com/photo-1532012197267-da84d127e765?w=1200&auto=format&fit=crop&q=80', 'Maomao, an eccentric young apothecary kidnapped and forced into imperial palace service, solves medical and political mysteries using her sharp analytical intellect.', 16, 'Ongoing', 'Trending', '["Seinen","Historical","Mystery","Slice of life"]', 9800, 120, 7600, 4.90),
(8, 'LORD OF THE MYSTERIES', 'Cuttlefish That Loves Diving', '/img/download (1).jpg', 'https://images.unsplash.com/photo-1514539079130-25950c84af65?w=1200&auto=format&fit=crop&q=80', 'Awakening in a Victorian steampunk world full of eldritch horrors and Beyonder potions, Zhou Mingrui assumes the persona of Klein Moretti and forms the mysterious Tarot Club.', 8, 'Completed', 'Trending', '["Fantasy","Supernatural","Horror","Mystery"]', 13400, 150, 11200, 4.92),
(9, 'KAIJU NO. 8', 'Naoya Matsumoto', '/img/download (2).jpg', 'https://images.unsplash.com/photo-1563089145-599997674d42?w=1200&auto=format&fit=crop&q=80', 'Kafka Hibino, a 32-year-old monster-cleanup worker, gains the ability to transform into a Kaiju himself and finally pursues his childhood dream of joining the Defense Force.', 15, 'Completed', 'Trending', '["Action","Sci-Fi","Comedy","Shonen"]', 8900, 210, 6200, 4.75),
(10, 'SPY X FAMILY', 'Tatsuya Endo', '/img/download (4).jpg', 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=1200&auto=format&fit=crop&q=80', 'Master spy Twilight constructs a fake family including a telepathic daughter and an assassin wife for a covert mission, unaware that both hold secret double lives.', 13, 'Ongoing', 'Trending', '["Action","Comedy","Slice of life","School"]', 18500, 230, 14100, 4.88),
(11, 'NARUTO', 'Masashi Kishimoto', '/img/naruto manga cover.jpg', 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=1200&auto=format&fit=crop&q=80', 'Naruto Uzumaki, a hyperactive young ninja harboring the Nine-Tailed Fox monster inside him, strives to gain respect and realize his dream of becoming Hokage.', 72, 'Completed', 'Old but Gold', '["Shonen","Action","Adventure","Supernatural"]', 38000, 510, 27500, 4.85),
(12, 'HUNTER X HUNTER', 'Yoshihiro Togashi', '/img/hunter x hunter.jpg', 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1200&auto=format&fit=crop&q=80', 'Gon Freecss discovers his long-lost father is a world-famous Hunter. Gon takes the brutal Hunter Examination to follow in his father\'s footsteps and unlock Nen mastery.', 38, 'Ongoing', 'Old but Gold', '["Shonen","Action","Adventure","Fantasy"]', 24500, 310, 19200, 4.92),
(13, 'BLACK CLOVER', 'Yuki Tabata', '/img/download (3).jpg', 'https://images.unsplash.com/photo-1514539079130-25950c84af65?w=1200&auto=format&fit=crop&q=80', 'Asta, an orphan born without a drop of magic in a world where magic is everything, receives a rare five-leaf clover grimoire containing anti-magic power.', 36, 'Ongoing', 'Old but Gold', '["Shonen","Action","Fantasy"]', 11400, 340, 8900, 4.70),
(14, 'BLEACH', 'Tite Kubo', '/img/BLEACH POSTER_.jpg', 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=1200&auto=format&fit=crop&q=80', 'High schooler Ichigo Kurosaki gains Soul Reaper powers from Rukia Kuchiki and takes on the duty of defending humans from evil spirits known as Hollows.', 74, 'Completed', 'Old but Gold', '["Shonen","Action","Supernatural","Dark Fantasy"]', 29800, 490, 21000, 4.80),
(15, 'DEATH NOTE', 'Tsugumi Ohba', '/img/download (1).jpg', 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=1200&auto=format&fit=crop&q=80', 'Genius high school student Light Yagami finds a supernatural notebook that kills anyone whose name is written in it, sparking a deadly battle of wits with detective L.', 12, 'Completed', 'Old but Gold', '["Supernatural","Seinen","Horror","Dark Fantasy"]', 31000, 350, 24000, 4.91)
ON DUPLICATE KEY UPDATE title=VALUES(title), author=VALUES(author), coverImage=VALUES(coverImage), bannerImage=VALUES(bannerImage), synopsis=VALUES(synopsis), totalVolumes=VALUES(totalVolumes), status=VALUES(status), category=VALUES(category), genres=VALUES(genres), likeAmount=VALUES(likeAmount), dislikeAmount=VALUES(dislikeAmount), favoriteAmount=VALUES(favoriteAmount), rating=VALUES(rating);
